# Generated by Django 4.2.1 on 2023-05-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_category_watch_list_comments_bids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='auction_listings/'),
        ),
    ]
