# Generated by Django 4.2.1 on 2023-05-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
