# Generated by Django 4.2.1 on 2023-05-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_listings_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
