# Generated by Django 4.2.1 on 2023-05-30 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_listings_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='listed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
