# Generated by Django 4.2.1 on 2023-05-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_listings_listed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
