# Generated by Django 4.2.1 on 2023-06-02 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_listings_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='sold_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.bids'),
        ),
    ]
