# Generated by Django 4.2.1 on 2023-06-02 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auction_listings_sold_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bids'),
        ),
    ]
