# Generated by Django 4.2.1 on 2023-06-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_auction_listings_sold_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='sold_to',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
