# Generated by Django 4.2.1 on 2023-06-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_auction_listings_sold_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
